const NeedHelpEnum = {
  ANALYSE_USER: "Analyse User",
  ANALYSE_FOLLOWER_FOLLOWING: "Analyse Follower Following",
  ANALYSE_POSTS: "Analyse Posts",
  DEAD_FOLLOWERS: "Dead followers",
  COMMON_USERS: "common users",
  REPOST: "Repost",
  HEART_YOUR_IMAGE: "Heart your Image",
  RELATED_HASHTAGS: "Related Hashtags",
  SPLIT_IMAGE: "Split Image",
  AUTOMATION_CONFIGURATIONS: "Automation Configuration",
  TASK_QUEUE: "Task Queue",
  COMMENT_STORE: "Comment Store",
  ACTIONS_BY_USERNAME: "Actions By Username",
  LIKE_COMMENT_BY_FEED: "Like Comment By Feed",
  IG_ACTIVITY_STATISTICS: "IG Activity & Statistics",
  EXPLORE_INSTA_HASHTAGS: "Explore Instagram Hashtags",
  EXPLORE_INSTA_LOCATIONS: "Explore Instagram Locations",
  ANALYSE_USER_LIKER_COMMENTER: "Analyse User wise Likers Commenters",
  ANALYSE_POST_LIKER_COMMENTER: "Analyse Post wise Liker Commenters",
  DETAILED_USER_ANALYSIS: "Detailed User Analysis",
  TRENDING_CONTENT: "Trending Content",
  GIVEAWAY_WINNER: "Giveaway Winner",
  EXPLAINER_ANALYTICS: "Analytics Explainer",
  EXPLAINER_IMPROVE_CONTENT: "Explainer Improve Content",
  EXPLAINER_ENGAGE: "Explainer for Engage with Audience",
};

export default NeedHelpEnum;
